replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/aws-discovery
  tag: ~
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

extraEnv: []
# - name: foo
#   value: bar
sentry_dsn: "https://48bfc9553f1c4a1a867d836d0558f2dd@o322024.ingest.sentry.io/5379362"
global:
  groupId: ~

deployment:
  enabled: false

cronJob:
  enabled: false
  schedule: "*/30 * * * *"

priorityClass:
  create: false
  priority: -1000
  baseName: aws-discovery-svc

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 1Gi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50
nodeSelector: {}

tolerations: []

affinity: {}
