{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "graph-explorer.serviceAccountName" . }}
  labels:
{{ include "graph-explorer.labels" . | indent 4 }}
{{- end -}}
