apiVersion: v1
kind: Secret
metadata:
  name: {{ template "arcade-analytics.fullname" . }}-secret
  labels:
    app: {{ template "arcade-analytics.name" . }}
    chart: {{ template "arcade-analytics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  root-password: {{ .Values.odbRootPassword | b64enc | quote }}
