{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "arcade-analytics.serviceAccountName" . }}
  labels:
{{ include "arcade-analytics.labels" . | indent 4 }}
{{- end -}}
