{{- $vMap := $.Chart.Version | split "." -}}
{{- $imageTag := .Values.image.tag | default (index $vMap "_1") -}}
{{- $fullName := include "arcade-analytics.fullname" . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
{{ include "arcade-analytics.labels" . | indent 4 }}
spec:
  serviceName: {{ $fullName }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arcade-analytics.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arcade-analytics.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "arcade-analytics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /management/health
              port: 8080
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod-single
            - name: SPRING_EMAIL_HOST
              value: ""
            - name: SPRING_EMAIL_PORT
              value: ""
            - name: SPRING_EMAIL_USERNAME
              value: ""
            - name: SPRING_EMAIL_PASSWORD
              value: ""
            - name: JHNIPSTER_MAIL_FROM
              value: ""
            - name: JHNIPSTER_MAIL_BASE-URL
              value: ""
            - name: MANAGEMENT_PORT
              value: '8080'
            - name: SERVER_PORT
              value: '80'
            - name: SERVER_CONTEXT_PATH
              value: {{ include "SERVER_CONTEXT_PATH" . }}
            - name: APPLICATION_PATH
              value: /arcade
            - name: APPLICATION_STORAGE_PATH
              value: /arcade/storage
            - name: APPLICATION_MEDIAPATH
              # be careful, this is not a filesystem path, it's a "URL"
              value: /content/media/
            - name: APPLICATION_CONNECTORSPATH
              value: /arcade-connectors
          {{ if .Values.persistence.enabled }}
          volumeMounts:
          - name: storage
            mountPath: /arcade
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: {{ .Values.persistence.accessModes }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
{{- end}}
