apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.fullname" . }}-configmap
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
data: 
  SENTRY_ENVIRONMENT: {{ .Values.global.groupId | quote }}
  SENTRY_RELEASE: {{ .Chart.Version | quote }}
  SENTRY_EXTRA: "groupId:{{ .Values.global.groupId }}"
{{- range $key, $value := .Values.mimir.config }}
  {{ $key -}}: {{ $value | quote -}}
{{ end }}
