apiVersion: v1
appVersion: "0.0.0"
description: A Helm chart to install the ec2 discovery service
name: ec2-discovery-svc
# Minor version is our image tag, no need to set in values
# Please use patch for multiple revs of a specific build
version: 0.2257.0
