# Default values for cluster-upgrade.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/cluster-upgrade
  # Pulled from minor value in Chart.yaml version:
  tag: ~
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

sentry_dsn: https://54e5f8625c5e4fdba66c69eb47bf9e1a@o322024.ingest.sentry.io/5367691
global:
  adminClientId: ~
  adminClientSecret: ~
  asgardUrl: https://api.openraven.com
  certManagerAwsKey: ~
  certManagerAwsRegion: ~
  certManagerAwsSecret: ~
  certManagerDomain: ~
  certManagerEmail: ~
  certManagerZoneId: ~
  clusterName: ~
  cookieSecret: ~
  frontEndClientId: ~
  groupId: ~
  serviceClientId: ~
  serviceClientSecret: ~
  openravenIngressHostname: ~

helmS3Bucket: ~
# openraven-deploy
helmS3Key: ~
# charts/helmfile.yaml
helmS3Region: ~
# us-west-2

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  name: "cluster-upgrade-sa"

schedules:
  tlsRefresh: 0 0 * * *

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 1Gi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=100

nodeSelector: {}

tolerations: []

affinity: {}
