{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ include "cluster-upgrade.fullname" . }}
    labels:
{{ include "cluster-upgrade.labels" . | indent 8 }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: {{ template "cluster-upgrade.serviceAccountName" . }}
      namespace: "{{ .Release.Namespace }}"
{{- end -}}
