{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cluster-upgrade.serviceAccountName" . }}
  labels:
{{ include "cluster-upgrade.labels" . | indent 4 }}
{{- end -}}
