# Default values for asset-groups.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/policy-service-repo-docker
  # Pulled from minor value in Chart.yaml version:
  tag: ~
  pullPolicy: IfNotPresent

global:
  groupId: ~

sentry_dsn: https://60337d192ae74aacbe9b16fb6426dbc6@o322024.ingest.sentry.io/5465446

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
  hosts:
    - host: ~ #Check in ingress.yaml
      paths:
      - /api/rules
      - /api/policies

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: 0.5Gi
  limits:
    memory: 0.5Gi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75

nodeSelector: {}

tolerations: []

affinity: {}

# OPA Values
opa:
  name: opa
  image: docker.io/openpolicyagent/opa
  imageTag: 0.15.1
  pullPolicy: IfNotPresent
  port: 8081
  mgmt:
    port: 8082
    enabled: true
  logLevel: info
  logFormat: text
  prometheus:
    enabled: false
    port: 8083
  extraArgs: []
  resources:
    requests:
      memory: 0.5Gi
    limits:
      memory: 0.5Gi
