apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-discovery-svc.fullname" . }}
  labels:
{{ include "s3-discovery-svc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "s3-discovery-svc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "s3-discovery-svc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{ $vMap := $.Chart.Version | split "." }}
          image: "{{.Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag | default $vMap._1 }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                "openraven":{
                  "app": {
                    "v1":{
                      "assets-consumer":{
                        "sendToElasticsearch":{
                          "enabled": false
                          }
                        }
                      }
                    }
                  },
                  "management": {
                    "health": {
                      "elasticsearch": {
                        "enabled": false
                      }
                    },
                    "server": {
                      "port": 8080
                    }
                  },
                  "server": {
                    "port": 80
                  }
                }
            - name: SPRING_PROFILES_ACTIVE
              value: default, producer, consumer, prod
            - name: GREMLIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root-password
                  name: {{ include "s3-discovery-svc.fullname" . }}-secret
            - name: OPENRAVEN_APP_V1_CLOUD-INGESTION_ANALYTICS_CLUSTERID
              value: {{ .Values.global.groupId }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
