---
# Source: cross-account/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-cross-account
  labels:
    app.kubernetes.io/name: cross-account
    helm.sh/chart: cross-account-0.253231769.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cross-account
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: cross-account/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-cross-account
  labels:
    app.kubernetes.io/name: cross-account
    helm.sh/chart: cross-account-0.253231769.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cross-account
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cross-account
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        ad.datadoghq.com/cross-account.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/cross-account.init_configs: |
          [{}]
        ad.datadoghq.com/cross-account.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8080/actuator/prometheus",
              "namespace": "cross-account",
              "metrics": ["*"]
            }
          ]
        iam.amazonaws.com/role: "orvn--cross-account"
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: cross-account
          securityContext:
            {}
          image: "registry.gitlab.com/openraven/open/cross-account:253231769"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            limits:
              memory: 1G
            requests:
              memory: 1G
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default, prod
            - name: MANAGEMENT_SERVER_PORT
              value: "8080"
            - name: SERVER_PORT
              value: "80"
            - name: SERVER_MAX-HTTP-HEADER-SIZE
              value: "128KB"
            - name: OPENRAVEN_APP_V1_CLOUD-INGESTION_ANALYTICS_CLUSTERID
              value: 
            - name: SENTRY_DSN
              value: "https://49533685193541daacc31a0c86e6bb11@o322024.ingest.sentry.io/5264893"
            - name: SENTRY_EXTRA
              value: "groupId:"
            - name: SENTRY_RELEASE
              value: "0.253231769.0"
            - name: SERVICE_CLIENT_ID
              value: 
            - name: SERVICE_CLIENT_SECRET
              value: 
            - name: JAVA_TOOL_OPTIONS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=90
---
# Source: cross-account/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-cross-account
  labels:
    app.kubernetes.io/name: cross-account
    helm.sh/chart: cross-account-0.253231769.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /accounts/cross-account
            backend:
              serviceName: RELEASE-NAME-cross-account
              servicePort: 80
---
# Source: cross-account/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-cross-account-test-connection"
  labels:
    app.kubernetes.io/name: cross-account
    helm.sh/chart: cross-account-0.253231769.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['RELEASE-NAME-cross-account:80']
  restartPolicy: Never
