---
# Source: s3-scan-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-s3-scan-service
  labels:
    app.kubernetes.io/name: s3-scan-service
    helm.sh/chart: s3-scan-service-0.270944809.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: s3-scan-service
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: s3-scan-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-s3-scan-service
  labels:
    app.kubernetes.io/name: s3-scan-service
    helm.sh/chart: s3-scan-service-0.270944809.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: s3-scan-service
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s3-scan-service
        app.kubernetes.io/instance: RELEASE-NAME
      annotations:
        ad.datadoghq.com/s3-scan-service.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/s3-scan-service.init_configs: |
          [{}]
        ad.datadoghq.com/s3-scan-service.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:8080/actuator/prometheus",
              "namespace": "s3-scan-service",
              "metrics": ["*"]
            }
          ]
        iam.amazonaws.com/role: "orvn--s3-scan-service"
    spec:
      containers:
        - name: s3-scan-service
          
          image: "registry.gitlab.com/openraven/open/s3-scan-service-repo-docker:270944809"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default,prod
            - name: MANAGEMENT_SERVER_PORT
              value: '8080'
            - name: JAVA_TOOL_OPTIONS
              value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70
            - name: SENTRY_DSN
              value: "https://eea6b3c7bbcb4b9cbbdfccef714d42cd@o322024.ingest.sentry.io/5406671"
            - name: SENTRY_ENVIRONMENT
              value: 
            - name: SENTRY_RELEASE
              value: "0.270944809.0"
            - name: SENTRY_EXTRA
              value: "groupId:"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ASGARD_CLIENT-ID
              value: 
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ASGARD_CLIENT-SECRET
              value: 
            - name: OPENRAVEN_APP_V1_CLUSTER_NAME
              value: 
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
---
# Source: s3-scan-service/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-s3-scan-service
  labels:
    app.kubernetes.io/name: s3-scan-service
    helm.sh/chart: s3-scan-service-0.270944809.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-request-user, x-auth-request-email, x-auth-request-access-token
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
      auth_request_set $bearer_token $upstream_http_x_auth_request_access_token;
      proxy_set_header authorization 'Bearer $bearer_token';
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /api/data-identifiers
            backend:
              serviceName: RELEASE-NAME-s3-scan-service
              servicePort: 80
          - path: /api/s3scan
            backend:
              serviceName: RELEASE-NAME-s3-scan-service
              servicePort: 80
---
# Source: s3-scan-service/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-s3-scan-service-test-connection"
  labels:
    app.kubernetes.io/name: s3-scan-service
    helm.sh/chart: s3-scan-service-0.270944809.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['RELEASE-NAME-s3-scan-service:80']
  restartPolicy: Never
