 # Default values for dmap
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/dmap
  #Pulled from minor value in version
  tag: ~
  pullPolicy: IfNotPresent

global:
  groupId: ~

sentry_dsn: https://d557df44b5df4057bac234d40efbadde@o322024.ingest.sentry.io/5379389

#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: #Check in ingress.yml
      paths:
      - /api/dmap/scanner
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

ingressauth:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization, x-auth-request-access-token"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";
  hosts:
    - host: #Check in ingress.yml
      paths:
      - /api/dmap
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 1Gi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70

nodeSelector: {}

tolerations: []

affinity: {}
