ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    ingress.kubernetes.io/proxy-body-size: 50m
    ingress.kubernetes.io/proxy-request-buffering: "off"
  hosts:
    - host: ~
  tls: []

kibana_route: /kibana
kibana_service: kibana
elasticsearch_route: /elasticsearch
elasticsearch_service: elasticsearch
controller_version: 1.1.1

# These values have been moved to helmfile.d/elasticsearch.yaml
# Please go look there before setting these values, as there be dragons
nodeCount: ~
nodeSetName: ~
storageRequest: ~
storageClassName: ~
