ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    ingress.kubernetes.io/proxy-body-size: 50m
    ingress.kubernetes.io/proxy-request-buffering: "off"
  hosts:
    - host: ~
  tls: []

kibana_route: /kibana
kibana_service: kibana
elasticsearch_route: /elasticsearch
elasticsearch_service: elasticsearch
controller_version: 1.1.1

nodeCount: 3
# Using -003 since the name must be valid DNS.
# When increasing the disk size, rev the name of the nodeset.
# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-orchestration-limitations
nodeSetName: default-003
storageRequest: 100Gi
storageClassName: default-storage-class
