apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aws-discovery-svc.fullname" . }}-secret
  labels:
    app: {{ template "aws-discovery-svc.name" . }}
    chart: {{ template "aws-discovery-svc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  root-password: {{ .Values.odbRootPassword | b64enc | quote }}
