{{- $vMap := $.Chart.Version | split "." -}}
{{- $imageTag := .Values.image.tag | default $vMap._1 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elastic-search-node-client.fullname" . }}
  labels:
{{ include "elastic-search-node-client.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elastic-search-node-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elastic-search-node-client.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "elastic-search-node-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: config-template
        image: {{ .Values.elasticsearch.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--input=s3://{{ .Values.elasticsearch.bucketname }}/{{ .Values.elasticsearch.keyprefix }}/configtemplate.json"
        - "--output={{ .Values.elasticsearch.url }}/configservice"
        - "--type=template"
      - name: assetgroup-template
        image: {{ .Values.elasticsearch.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--input=s3://{{ .Values.elasticsearch.bucketname }}/{{ .Values.elasticsearch.keyprefix }}/assetgrouptemplate.json"
        - "--output={{ .Values.elasticsearch.url }}/assetgroup"
        - "--type=template"
      - name: assetgroup-data
        image: {{ .Values.elasticsearch.image }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--input=s3://{{ .Values.elasticsearch.bucketname }}/{{ .Values.elasticsearch.keyprefix }}/assetgroups.json"
        - "--output={{ .Values.elasticsearch.url }}/assetgroup"
        - "--type=data"
      - name: kibana-dashboards
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: registry.gitlab.com/openraven/open/build-image:131116232
        command:
          - /bin/bash
          - -exc
          - |
            aws s3 cp s3://{{ .Values.elasticsearch.bucketname }}/{{ .Values.elasticsearch.keyprefix }}/dashboards.ndjson .
            curl -XPOST -H "kbn-xsrf: true" --form file=@dashboards.ndjson -fsSL {{ .Values.kibana_url }}/api/saved_objects/_import
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ELASTIC_URL
              value: {{ .Values.elastic_url}}
            {{- with .Values.elastic_username }}
            - name: USERNAME
              value: {{ .Values.elastic_username }}
            - name: PASSWORD
              value: {{ .Values.elastic_password }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /es/ping
              port: http
          readinessProbe:
            httpGet:
              path: /es/ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
