{{ $vMap := $.Chart.Version | split "." }}
{{- $imageTag := .Values.image.tag | default (index $vMap "_1") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudwatcher.fullname" . }}
  labels:
    {{- include "cloudwatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudwatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudwatcher.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cloudwatcher.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default, prod, extractor
            - name: MANAGEMENT_SERVER_PORT
              value: "8080"
            - name: SERVER_PORT
              value: "80"
            - name: SERVER_MAX-HTTP-HEADER-SIZE
              value: "128KB"
            - name: SENTRY_DSN
              value: "{{ .Values.sentry_dsn }}"
            - name: SENTRY_EXTRA
              value: "groupId:{{ .Values.global.groupId }}"
            - name: SENTRY_RELEASE
              value: "{{ .Chart.Version }}"
            - name: OPENRAVEN_APP_V1_CLOUD-INGESTION_ANALYTICS_CLUSTERID
              value: {{ .Values.global.groupId }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.java.vmArgs }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
