{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudwatcher.serviceAccountName" . }}
  labels:
{{ include "cloudwatcher.labels" . | nindent 4 }}
{{- end -}}
