apiVersion: v1
appVersion: "0.0.0"
description: A Helm chart to install the integrations service
name: integrations
# Minor version is our image tag, no need to set in values
# Please use patch for multiple revs of a specific build
version: 0.232109562.0
