 # Default values for integrations
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/integrations-service-repo-docker
  #Pulled from minor value in version
  tag: ~
  pullPolicy: IfNotPresent

global:
  adminClientId: ~
  adminClientSecret: ~
  groupId: ~
  openravenIngressHostname: ~

sentry_dsn: https://eea6b3c7bbcb4b9cbbdfccef714d42cd@o322024.ingest.sentry.io/5406671

#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header cookie "";
      auth_request_set $auth_cookie $upstream_http_set_cookie;
      add_header Set-Cookie $auth_cookie;
  hosts:
    - host: ~ #Check in ingress.yaml
      paths: ["/api/integrations"]

resources:
  requests:
    memory: 1Gi
  limits:
    memory: 1Gi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70

nodeSelector: {}

tolerations: []

affinity: {}
