 # Default values for integrations
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/integrations-service-repo-docker
  #Pulled from minor value in version
  tag: ~
  pullPolicy: IfNotPresent

global:
  adminClientId: ~
  adminClientSecret: ~
  groupId: ~
  openravenIngressHostname: ~

sentry_dsn: https://f7b2669a7437459aa7632ba39772d3d3@o322024.ingest.sentry.io/5563380

#imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: ~ #Check in ingress.yaml
      paths: ["/api/integrations/test"]

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 512Mi
java:
  vmArgs: -XX:+UseContainerSupport -XX:MaxRAMPercentage=70

nodeSelector: {}

tolerations: []

affinity: {}
