{{ $vMap := $.Chart.Version | split "." }}
{{- $imageTag := .Values.image.tag | default $vMap._1 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "account-management.fullname" . }}
  labels:
{{ include "account-management.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "account-management.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "account-management.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "account-management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default, prod
            - name: MANAGEMENT_SERVER_PORT
              value: "8080"
            - name: SERVER_PORT
              value: "80"
            - name: SERVER_MAX-HTTP-HEADER-SIZE
              value: "128KB"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT-ID
              value: {{ .Values.global.adminClientId }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT-SECRET
              value: {{ .Values.global.adminClientSecret}}
            - name: OPENRAVEN_APP_V1_CLUSTER_ADMIN-CLIENT-ID
              value: {{ .Values.global.adminClientId }}
            - name: OPENRAVEN_APP_V1_CLUSTER_ADMIN-CLIENT-SECRET
              value: {{ .Values.global.adminClientSecret}}
            - name: OPENRAVEN_APP_V1_CLUSTER_NAME
              value: {{ .Values.global.clusterName | quote }}
            - name: SENTRY_RELEASE
              value: "{{ .Chart.Version }}"
            - name: SENTRY_EXTRA
              value: "groupId:{{ .Values.global.groupId }}"
            - name: SEGMENT_ANALYTICS_WRITEKEY
              value: mLZedQqPeRGL19unziVuoVQXDXjMl94F
            - name: OPENRAVEN_APP_V1_CLOUD-INGESTION_ANALYTICS_CLUSTERID
              value: {{ .Values.global.groupId }}
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.java.vmArgs }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
