replicaCount: 1

image:
  registry: registry.gitlab.com
  repository: openraven/open/mimir-repo-docker
  pullPolicy: IfNotPresent
  # Pulled from minor value in Chart.yaml version:
  tag: ~

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

mimir_route: /mimir

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: ~
  tls: []

resources:
   limits:
     cpu: 1
     memory: 2Gi
   requests:
     cpu: 1
     memory: 2Gi

jobresources:
   limits:
     cpu: 250m
     memory: 128Mi
   requests:
     cpu: 250m
     memory: 128Mi

curl_image: "curlimages/curl:7.70.0"

schedules:
  organizationjob: "5 * * * *"
  snapshotjob: "35 * * * *"
  configjob: "15 * * * *"

nodeSelector: {}

tolerations: []

affinity: {}

mimir:
  config:
    JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=100"
    SERVER_MAX-HTTP-HEADER-SIZE: "128KB"
    MANAGEMENT_SERVER_PORT: 8080
    SERVER_PORT: 80
    SENTRY_DSN: https://87926994fc9b41b8af0e2357081239b1@o322024.ingest.sentry.io/5256089
