{{- $vMap := $.Chart.Version | split "." -}}
{{- $imageTag := .Values.image.tag | default (index $vMap "_1") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "policy.fullname" . }}
  labels:
{{ include "policy.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "policy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "policy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        ad.datadoghq.com/{{ .Chart.Name }}.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/{{ .Chart.Name }}.init_configs: |
          [{}]
        ad.datadoghq.com/{{ .Chart.Name }}.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:{{ .Values.serverManagementPort }}/actuator/prometheus",
              "namespace": "{{ .Chart.Name }}",
              "metrics": ["*"]
            }
          ]
        ad.datadoghq.com/opa.check_names: |
          ["openmetrics"]
        ad.datadoghq.com/opa.init_configs: |
          [{}]
        ad.datadoghq.com/opa.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:{{ .Values.opa.mgmt.port  }}/metrics",
              "namespace": "opa",
              "metrics": ["*"]
            }
          ]
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "policy.serviceAccountName" . }}
      securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.serverManagementPort }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.serverManagementPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default,prod
            - name: SERVER_PORT
              value: "80"
            - name: MANAGEMENT_SERVER_PORT
              value: "{{ .Values.serverManagementPort }}"
            - name: MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED
              value: "false"
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.java.vmArgs }}
            - name: SENTRY_DSN
              value: {{ .Values.sentry_dsn | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.global.groupId }}
            - name: SENTRY_RELEASE
              value: "{{ .Chart.Version }}"
            - name: SENTRY_EXTRA
              value: "groupId:{{ .Values.global.groupId }}"
        - name: {{ .Values.opa.name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{ with .Values.opa }}
          image: {{ .image }}:{{ .imageTag }}
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .port }}
              protocol: TCP
          {{- if .mgmt.enabled }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .mgmt.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .mgmt.port }}
          {{- end }}
          args:
            - "run"
            - "--server"
            - "--addr=0.0.0.0:{{ .port }}"
            - "--log-level={{ .logLevel }}"
            - "--log-format={{ .logFormat }}"
            {{- if .prometheus.enabled }}
            - "--addr=http://0.0.0.0:{{ .prometheus.port }}"
            {{- end }}
            {{- if .mgmt.enabled }}
            - "--addr=http://0.0.0.0:{{ .mgmt.port }}"
            {{- end }}
            {{- range .extraArgs }}
            - {{ . }}
            {{- end }}
          resources:
          {{- toYaml .resources | nindent 12 }}
          {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
