{{- $vMap := $.Chart.Version | split "." -}}
{{- $imageTag := .Values.image.tag | default $vMap._1 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "productui.fullname" . }}
  labels:
{{ include "productui.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "productui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "productui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "productui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{ if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{ end }}
          {{ if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{ if .Values.global.wantFrontendClientId }}
          volumeMounts:
          - name: envjs
            mountPath: /app/build/runtime-env.js
            subPath: runtime-env.js
            readOnly: true
          {{ end }}
      {{ if .Values.global.wantFrontendClientId }}
      volumes:
        - name: envjs
          configMap:
            name: {{ .Release.Name }}
            items:
              - key: runtime-env.js
                path: runtime-env.js
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
