{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "productui.serviceAccountName" . }}
  labels:
{{ include "productui.labels" . | indent 4 }}
{{- end -}}
