{{ $vMap := $.Chart.Version | split "." }}
{{- $imageTag := .Values.image.tag | default $vMap._1 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cross-account.fullname" . }}
  labels:
{{ include "cross-account.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cross-account.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cross-account.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "cross-account.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry }}/{{ .Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # this env-var is a formal standard:
            # https://docs.oracle.com/en/java/javase/11/troubleshoot/environment-variables-and-system-properties.html#GUID-A91E7E21-2E91-48C4-89A4-836A7C0EE93B
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.java.java_tool_options }}"
            - name: SPRING_PROFILES_ACTIVE
              value: default, prod
            - name: MANAGEMENT_SERVER_PORT
              value: "8080"
            - name: SERVER_PORT
              value: "80"
            - name: SERVER_MAX-HTTP-HEADER-SIZE
              value: "128KB"
            - name: OPENRAVEN_APP_V1_CLOUD-INGESTION_ANALYTICS_CLUSTERID
              value: {{ .Values.global.groupId }}
            - name: SERVICE_CLIENT_ID
              value: {{ .Values.global.serviceClientId }}
            - name: SERVICE_CLIENT_SECRET
              value: {{ .Values.global.serviceClientSecret }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
